// "use client"
// import localFont from "next/font/local";
// import DrawerAppBar from './components/Header';
// import "./globals.css";
// import ChatWidget from "./components/ChatWithUs";


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <div>
//           <DrawerAppBar/>
//         </div>
//         {children}
//       <ChatWidget></ChatWidget>
//       </body>
//     </html>
//   );
// }


"use client"
import localFont from "next/font/local";
import DrawerAppBar from './components/Header';
import "./globals.css";
import ChatWidget from "./components/ChatWithUs";
import { useState, useEffect } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function RootLayout({ children }) {
  const [headerHeight, setHeaderHeight] = useState(0);

  useEffect(() => {
    // Dynamically calculate the height of the header
    const headerElement = document.getElementById("header");
    if (headerElement) {
      setHeaderHeight(headerElement.offsetHeight);
    }
  }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div id="header">
          <DrawerAppBar />
        </div>
        
        {/* Ensure the main content is pushed below the header */}
        <div style={{ paddingTop: `${headerHeight}px` }}>
          {children}
        </div>

        <ChatWidget />
      </body>
    </html>
  );
}
